spring:
  profiles:
    active: anywhere
  #    active: @env.type@,@env.anywhere@

  datasource:
    url: jdbc:mysql://10.0.24.2:3306/anywhere?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
    username: anywhere
    password: anywhere19781978

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080
  servlet:
    context-path: /sample-jdbc
