spring:
  profiles:
    active: @env.type@,@env.anywhere@

  redis:
#    url: redis://10.0.24.2:6379
    host: 10.0.24.2
#    host: localhost
#    port: 6379
    connect-timeout: 10s
    timeout: 10s
    password: f8G8FaUOoTwZl9H7pRYd
#    redisson:
#      file: classpath:redisson.yaml
